version: '3.8'

services:
  tests:
    build: .
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      - PYTHONPATH=/app

  allure:
    image: frankescobar/allure-docker-service:latest
    ports:
      - "4040:5050"
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=3
      - KEEP_HISTORY=1
    volumes:
      - ./allure-results:/app/allure-results
    depends_on:
      - tests