[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.pytest_cache
  | allure-results
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3